
// 料理模板接口定义
export interface FoodRecipe {
  id: string;
  name: string;
  'main-res': string;
  'other-res': string[];
  img: string;
  description: string;
}

// 原始数据：料理配方与描述
export const FOOD_RECIPES: FoodRecipe[] = [
  { id: 'food_001', 'main-res': 'meat', 'other-res': [], img: '001_meat.png', name: '秘制烤肉排', description: '选用上等兽肉精心烤制，肉汁四溢，简单的调味反而衬托出肉质的鲜美。' },
  { id: 'food_002', 'main-res': 'meat', 'other-res': ['meat'], img: '002_meat-meat.png', name: '双层豪华肉排', description: '肉食主义者的终极梦想，两块厚切肉排叠在一起，带来双倍的满足感。' },
  { id: 'food_003', 'main-res': 'meat', 'other-res': [], img: '003_meat.png', name: '野味熏肉', description: '使用独家香料熏制的肉块，风味浓郁，是下酒的绝佳选择。' },
  { id: 'food_004', 'main-res': 'meat', 'other-res': [], img: '004_meat.png', name: '慢炖肉块', description: '经过长时间慢火炖煮，肉质酥软烂熟，入口即化。' },
  { id: 'food_005', 'main-res': 'meat', 'other-res': ['bean'], img: '005_meat-bean.png', name: '肉豆浓汤', description: '兽肉与豆类一同炖煮，汤汁浓稠，营养丰富，暖心又暖胃。' },
  { id: 'food_006', 'main-res': 'meat', 'other-res': ['rice', 'bean'], img: '006_meat-rice-bean.png', name: '肉排豆米套餐', description: '主料为肉排，搭配豆类和米饭制作的家常餐点，口味粗糙但量大管饱。' },
  { id: 'food_007', 'main-res': 'meat', 'other-res': ['rice', 'bean'], img: '007_meat-rice-bean.png', name: '什锦盖饭', description: '将炒过的碎肉和豆子铺在米饭上，淋上酱汁，深受冒险者喜爱。' },
  { id: 'food_008', 'main-res': 'meat', 'other-res': ['vegetable'], img: '008_meat-vegetable.png', name: '肉蔬小炒', description: '肉片与时令蔬菜大火快炒，荤素搭配，清爽不油腻。' },
  { id: 'food_009', 'main-res': 'meat', 'other-res': ['vegetable'], img: '009_meat-vegetable.png', name: '翡翠肉卷', description: '用蔬菜叶包裹调味肉馅蒸制而成，口感丰富。' },
  { id: 'food_010', 'main-res': 'meat', 'other-res': ['vegetable'], img: '010_meat-vegetable.png', name: '田园肉饼', description: '混合了切碎蔬菜的煎肉饼，既有肉香又有蔬菜的甘甜。' },
  { id: 'food_011', 'main-res': 'meat', 'other-res': ['vegetable', 'tomatoes'], img: '011_meat-vegetable-tomatoes.png', name: '番茄炖肉蔬', description: '酸甜的番茄汁渗透进肉和蔬菜中，开胃又下饭。' },
  { id: 'food_012', 'main-res': 'meat', 'other-res': ['vegetable', 'tomatoes', 'fruit'], img: '012_meat-vegetable-tomatoes-fruit.png', name: '果香红烩肉', description: '在番茄炖肉中加入水果提鲜，风味独特，口感层次丰富。' },
  { id: 'food_013', 'main-res': 'meat', 'other-res': ['carrot', 'potato'], img: '013_meat-carrot-potato.png', name: '经典炖菜', description: '肉块、胡萝卜和土豆的经典组合，旅途中最常见的美味。' },
  { id: 'food_014', 'main-res': 'meat', 'other-res': ['potato'], img: '014_meat-potato.png', name: '土豆烧肉', description: '土豆吸收了肉汁的精华，甚至比肉还要好吃。' },
  { id: 'food_015', 'main-res': 'meat', 'other-res': ['potato'], img: '015_meat-potato.png', name: '肉碎土豆泥', description: '绵密的土豆泥中混入炒香的肉碎，口感顺滑。' },
  { id: 'food_016', 'main-res': 'meat', 'other-res': ['carrot', 'potato'], img: '016_meat-carrot-potato.png', name: '根茎炖肉', description: '以根茎类蔬菜为主的炖肉，有着大地的朴实味道。' },
  { id: 'food_017', 'main-res': 'meat', 'other-res': ['potato'], img: '017_meat-potato.png', name: '香煎肉薯', description: '切块的肉和土豆煎至金黄，撒上香料，香气扑鼻。' },
  { id: 'food_018', 'main-res': 'meat', 'other-res': ['potato', 'vegetable'], img: '018_meat-potato-vegetable.png', name: '杂烩炖锅', description: '有什么放什么的大杂烩，意外地融合出了美妙的滋味。' },
  { id: 'food_019', 'main-res': 'meat', 'other-res': ['carrot', 'potato', 'milk', 'vegetable'], img: '019_meat-carrot-potato-milk-vegetable.png', name: '奶香炖菜', description: '加入牛奶炖煮的肉类和蔬菜，汤色奶白，味道醇厚。' },
  { id: 'food_020', 'main-res': 'meat', 'other-res': ['carrot', 'potato', 'vegetable', 'dairy'], img: '020_meat-carrot-potato-vegetable-dairy.png', name: '芝士焗炖菜', description: '在炖菜上铺满乳酪烤制，拉丝的芝士让人欲罢不能。' },
  { id: 'food_021', 'main-res': 'meat', 'other-res': ['carrot', 'potato', 'bean'], img: '021_mea-carrot-potato-bean.png', name: '农夫肉汤', description: '大量豆类和根茎蔬菜熬制的肉汤，劳作一天后的最佳补给。' },
  { id: 'food_022', 'main-res': 'meat', 'other-res': ['potato', 'mushroom'], img: '022_meat-potato-mushroom.png', name: '菌菇肉薯', description: '蘑菇的鲜味完美衬托了肉和土豆，山珍的美味。' },
  { id: 'food_023', 'main-res': 'meat', 'other-res': ['flour'], img: '023_meat-flour.png', name: '肉馅饼', description: '面皮包裹着满满的肉馅，咬一口汁水横流。' },
  { id: 'food_024', 'main-res': 'meat', 'other-res': ['flour'], img: '024_meat-flour.png', name: '炸肉排', description: '裹上面粉炸至酥脆的肉排，外酥里嫩。' },
  { id: 'food_026', 'main-res': 'meat', 'other-res': ['flour'], img: '026_meat-flour.png', name: '肉卷饼', description: '薄饼卷上烤肉，方便携带的美味。' },
  { id: 'food_027', 'main-res': 'meat', 'other-res': ['egg'], img: '027_meat-egg.png', name: '滑蛋肉片', description: '鲜嫩的鸡蛋包裹着肉片，口感滑嫩。' },
  { id: 'food_028', 'main-res': 'poultry', 'other-res': [], img: '028_poultry.png', name: '脆皮烤禽', description: '整只禽鸟烤至皮脆肉嫩，色泽金黄诱人。' },
  { id: 'food_029', 'main-res': 'poultry', 'other-res': [], img: '029_poultry.png', name: '白切禽肉', description: '保留禽肉原汁原味的烹饪方式，肉质鲜美。' },
  { id: 'food_030', 'main-res': 'poultry', 'other-res': ['fruit'], img: '030_poultry-fruit.png', name: '果味烤禽', description: '腹中填入水果烤制，果香渗入肉中，解腻增香。' },
  { id: 'food_031', 'main-res': 'poultry', 'other-res': ['tomatoes'], img: '031_poultry-tomatoes.png', name: '茄汁烩禽肉', description: '浓郁的番茄酱汁包裹着禽肉块，酸甜可口。' },
  { id: 'food_032', 'main-res': 'poultry', 'other-res': ['potato', 'tomatoes'], img: '032_poultry-potato-tomatoes.png', name: '红烩土豆鸡', description: '经典的家庭料理，土豆绵软，鸡肉入味。' },
  { id: 'food_033', 'main-res': 'fish', 'other-res': [], img: '033_fish.png', name: '盐烤海鱼', description: '仅用海盐调味的烤鱼，展现大海的原始风味。' },
  { id: 'food_034', 'main-res': 'fish', 'other-res': [], img: '034_fish.png', name: '清蒸鱼', description: '最大限度保留鱼肉的鲜嫩，清淡健康。' },
  { id: 'food_035', 'main-res': 'fish', 'other-res': [], img: '035_fish.png', name: '干煎鱼排', description: '外皮焦香，内里鲜嫩多汁的鱼排。' },
  { id: 'food_036', 'main-res': 'fish', 'other-res': [], img: '036_fish.png', name: '鱼生切片', description: '新鲜捕捞的鱼直接切片，极其考验鲜度。' },
  { id: 'food_037', 'main-res': 'fish', 'other-res': [], img: '037_fish.png', name: '炸鱼块', description: '金黄酥脆的炸鱼块，下酒神器。' },
  { id: 'food_038', 'main-res': 'fish', 'other-res': ['fruit'], img: '038_fish-fruit.png', name: '柠香烤鱼', description: '挤上柠檬汁的烤鱼，清新爽口。' },
  { id: 'food_039', 'main-res': 'fish', 'other-res': ['fruit'], img: '039_fish-fruit.png', name: '果味鱼柳', description: '搭配酸甜水果酱汁的嫩滑鱼柳。' },
  { id: 'food_040', 'main-res': 'fish', 'other-res': ['fruit'], img: '040_fish-fruit.png', name: '热带鱼排', description: '搭配热带水果 salsa 的煎鱼排，充满异域风情。' },
  { id: 'food_041', 'main-res': 'fish', 'other-res': ['fruit'], img: '041_fish-fruit.png', name: '酸甜鱼块', description: '炸鱼块裹上水果调制的酸甜汁。' },
  { id: 'food_042', 'main-res': 'fish', 'other-res': ['fruit', 'tomatoes'], img: '042_fish-fruit-tomatoes.png', name: '地中海烤鱼', description: '番茄与水果的组合，带来阳光般的味道。' },
  { id: 'food_043', 'main-res': 'fish', 'other-res': ['carrot', 'potato'], img: '043_fish-carrot-potato.png', name: '鱼肉炖菜', description: '用鱼肉代替红肉的炖菜，汤头更加鲜美。' },
  { id: 'food_044', 'main-res': 'fish', 'other-res': ['vegetable'], img: '044_fish-vegetable.png', name: '时蔬鱼卷', description: '鱼片卷裹蔬菜蒸制，造型精致。' },
  { id: 'food_045', 'main-res': 'fish', 'other-res': ['vegetable', 'fruit'], img: '045_fish-vegetable-fruit.png', name: '缤纷鱼沙拉', description: '煎鱼块搭配新鲜蔬果，色彩缤纷。' },
  { id: 'food_046', 'main-res': 'fish', 'other-res': ['potato', 'fruit'], img: '046_fish-potato-fruit.png', name: '果香鱼薯', description: '炸鱼薯条配上特制果酱，独特的搭配。' },
  { id: 'food_047', 'main-res': 'fish', 'other-res': ['carrot', 'potato', 'vegetable'], img: '047_fish-carrot-potato-vegetable.png', name: '渔夫炖锅', description: '渔民的家常菜，鱼获与蔬菜的一锅乱炖。' },
  { id: 'food_048', 'main-res': 'shrimp', 'other-res': [], img: '048_shrimp.png', name: '白灼鲜虾', description: '最简单的烹饪方式，最纯粹的鲜甜。' },
  { id: 'food_049', 'main-res': 'shrimp', 'other-res': ['bean'], img: '049_shrimp-bean.png', name: '虾仁豆烩', description: '虾仁与豆类的清新组合。' },
  { id: 'food_050', 'main-res': 'shrimp', 'other-res': ['fruit'], img: '050_shrimp-fruit.png', name: '凤梨虾球', description: '酥脆虾球配上酸甜凤梨，口感丰富。' },
  { id: 'food_051', 'main-res': 'shrimp', 'other-res': ['dairy', 'potato'], img: '051_shrimp-dairy-potato.png', name: '芝士焗虾薯', description: '土豆泥混合虾仁，铺上厚厚芝士焗烤。' },
  { id: 'food_052', 'main-res': 'shrimp', 'other-res': ['fish', 'mussel', 'carrot'], img: '052_shrimp-fish-mussel-carrot.png', name: '海鲜总汇', description: '汇集了多种海鲜的豪华拼盘。' },
  { id: 'food_053', 'main-res': 'mussel', 'other-res': [], img: '053_mussel.png', name: '清煮贝类', description: '保留海水咸鲜味的煮贝。' },
  { id: 'food_054', 'main-res': 'mussel', 'other-res': [], img: '054_mussel.png', name: '炭烤贝', description: '炭火烤制，贝肉紧致弹牙。' },
  { id: 'food_055', 'main-res': 'mussel', 'other-res': [], img: '055_mussel.png', name: '酒蒸贝', description: '加入少许酒水蒸煮，去腥提鲜。' },
  { id: 'food_056', 'main-res': 'mussel', 'other-res': [], img: '056_mussel.png', name: '辣炒贝类', description: '辛辣刺激的调味，让人一口接一口。' },
  { id: 'food_057', 'main-res': 'potato', 'other-res': [], img: '057_potato.png', name: '烤土豆', description: '简单的烤土豆，表皮焦脆内心绵软。' },
  { id: 'food_058', 'main-res': 'potato', 'other-res': ['dairy'], img: '058_potato-dairy.png', name: '黄油土豆', description: '融化的黄油渗入热腾腾的土豆，香气四溢。' },
  { id: 'food_059', 'main-res': 'potato', 'other-res': [], img: '059_potato.png', name: '炸薯条', description: '外酥里嫩的黄金条，零食界的王者。' },
  { id: 'food_060', 'main-res': 'potato', 'other-res': ['mushroom'], img: '060_potato-mushroom.png', name: '菌菇土豆泥', description: '拌入炒蘑菇的土豆泥，风味浓郁。' },
  { id: 'food_061', 'main-res': 'potato', 'other-res': ['meat'], img: '061_potato-meat.png', name: '培根土豆', description: '培根的油脂滋润了土豆，咸香可口。' },
  { id: 'food_062', 'main-res': 'potato', 'other-res': ['tomatoes'], img: '062_potato-tomatoes.png', name: '茄汁土豆', description: '酸甜开胃的番茄烧土豆。' },
  { id: 'food_063', 'main-res': 'potato', 'other-res': ['egg'], img: '063_potato-egg.png', name: '土豆烘蛋', description: '西班牙风味的厚蛋烧，夹杂着软糯土豆。' },
  { id: 'food_064', 'main-res': 'potato', 'other-res': ['bean', 'tomatoes'], img: '064_potato-bean-tomatoes.png', name: '红豆土豆烩', description: '番茄底的豆子土豆烩菜，素食者的美味。' },
  { id: 'food_065', 'main-res': 'potato', 'other-res': ['carrot', 'bean'], img: '065_potato-carrot-bean.png', name: '素食炖锅', description: '根茎蔬菜与豆类的清炖，健康养生。' },
  { id: 'food_066', 'main-res': 'potato', 'other-res': ['dairy', 'meat'], img: '066_potato-dairy-meat.png', name: '芝士肉酱薯', description: '淋上肉酱和芝士的烤土豆，热量炸弹。' },
  { id: 'food_067', 'main-res': 'potato', 'other-res': ['dairy'], img: '067_potato-dairy.png', name: '奶油焗土豆', description: '浸泡在奶油中烤制的土豆片，奶香浓郁。' },
  { id: 'food_068', 'main-res': 'potato', 'other-res': ['milk'], img: '068_potato-milk.png', name: '牛奶土豆泥', description: '加入大量牛奶搅打，细腻如丝的土豆泥。' },
  { id: 'food_069', 'main-res': 'potato', 'other-res': ['bean', 'dairy'], img: '069_potato-bean-dairy.png', name: '奶酪豆薯', description: '豆子和土豆裹上融化的奶酪。' },
  { id: 'food_070', 'main-res': 'potato', 'other-res': ['carrot', 'vegetable'], img: '070_potato-carrot-vegetable.png', name: '田园土豆饼', description: '混合各种蔬菜碎的煎土豆饼。' },
  { id: 'food_071', 'main-res': 'carrot', 'other-res': ['mushroom'], img: '071_carrot-mushroom.png', name: '胡萝卜炒菌', description: '简单清爽的素炒。' },
  { id: 'food_072', 'main-res': 'carrot', 'other-res': ['vegetable'], img: '072_carrot-vegetable.png', name: '清炒时蔬', description: '保留蔬菜原味的清淡料理。' },
  { id: 'food_073', 'main-res': 'carrot', 'other-res': ['vegetable', 'melons'], img: '073_carrot-vegetable-melons.png', name: '什锦素菜', description: '色彩鲜艳的素菜拼盘。' },
  { id: 'food_074', 'main-res': 'bean', 'other-res': [], img: '074_bean.png', name: '煮豆子', description: '简简单单的盐水煮豆。' },
  { id: 'food_075', 'main-res': 'bean', 'other-res': ['meat', 'potato'], img: '075_bean-meet-potato.png', name: '肉豆炖土豆', description: '经典的家常炖菜，饱腹感强。' },
  { id: 'food_076', 'main-res': 'flour', 'other-res': [], img: '076_flour.png', name: '原味烤饼', description: '仅用面粉和水烤制的硬面饼，耐储存。' },
  { id: 'food_077', 'main-res': 'flour', 'other-res': [], img: '077_flour.png', name: '发面饼', description: '蓬松柔软的发面饼。' },
  { id: 'food_078', 'main-res': 'flour', 'other-res': ['meat', 'dairy'], img: '078_flour-meat-dairy.png', name: '肉酱披萨', description: '铺满肉酱和芝士的面饼，聚会首选。' },
  { id: 'food_079', 'main-res': 'flour', 'other-res': ['tomatoes'], img: '079_flour-tomatoes.png', name: '番茄披萨', description: '经典的玛格丽特风味披萨。' },
  { id: 'food_080', 'main-res': 'flour', 'other-res': ['shrimp', 'mussel'], img: '080_flour-shrimp-mussel.png', name: '海鲜披萨', description: '大海的馈赠铺在酥脆饼底上。' },
  { id: 'food_081', 'main-res': 'flour', 'other-res': ['meat', 'milk'], img: '081_flour-meat-milk.png', name: '奶油肉酱面', description: '浓郁的白酱裹着面条和肉碎。' },
  { id: 'food_082', 'main-res': 'flour', 'other-res': ['shrimp', 'milk'], img: '082_flour-shrimp-milk.png', name: '白酱鲜虾面', description: '奶香浓郁的意面配上鲜甜虾仁。' },
  { id: 'food_083', 'main-res': 'flour', 'other-res': ['tomatoes', 'potato'], img: '083_flour-tomatoes-potato.png', name: '番茄土豆面疙瘩', description: '口感Q弹的面疙瘩配上酸甜汤底。' },
  { id: 'food_084', 'main-res': 'flour', 'other-res': ['meat', 'milk'], img: '084_flour-meat-milk.png', name: '肉馅派', description: '酥皮包裹着多汁肉馅的咸派。' },
  { id: 'food_085', 'main-res': 'flour', 'other-res': ['fruit'], img: '085_flour-fruit.png', name: '水果蛋挞', description: '酥脆挞皮盛着香甜水果。' },
  { id: 'food_086', 'main-res': 'flour', 'other-res': ['meat'], img: '086_flour-meat.png', name: '肉包', description: '松软面皮包裹着大团肉馅。' },
  { id: 'food_087', 'main-res': 'flour', 'other-res': ['dairy'], img: '087_flour-dairy.png', name: '芝士面包棒', description: '裹入芝士烘烤的面包棒，香脆可口。' },
  { id: 'food_088', 'main-res': 'flour', 'other-res': ['milk', 'fruit'], img: '088_flour-milk-fruit.png', name: '水果可丽饼', description: '薄薄的奶香饼皮卷着新鲜水果。' },
  { id: 'food_089', 'main-res': 'flour', 'other-res': ['dairy', 'fruit'], img: '089_flour-dairy-fruit.png', name: '乳酪水果塔', description: '奶油奶酪与水果的完美结合。' },
  { id: 'food_090', 'main-res': 'flour', 'other-res': ['dairy'], img: '090_flour-dairy.png', name: '芝士蛋糕', description: '重乳酪风味的绵密蛋糕。' },
  { id: 'food_091', 'main-res': 'flour', 'other-res': ['rice', 'dairy'], img: '091_flour-rice-dairy.png', name: '米布丁塔', description: '酥皮塔壳装着香甜的米布丁。' },
  { id: 'food_092', 'main-res': 'flour', 'other-res': ['egg', 'milk'], img: '092_flour-egg-milk.png', name: '松饼', description: '松软香甜的早餐松饼。' },
  { id: 'food_093', 'main-res': 'flour', 'other-res': ['egg', 'dairy'], img: '093_flour-egg-dairy.png', name: '舒芙蕾', description: '云朵般蓬松的法式甜点。' },
  { id: 'food_094', 'main-res': 'flour', 'other-res': ['egg', 'milk', 'dairy', 'fruit'], img: '094_flour-egg-milk-dairy-fruit.png', name: '豪华水果蛋糕', description: '层层奶油与水果堆叠的庆典蛋糕。' },
  { id: 'food_095', 'main-res': 'flour', 'other-res': ['egg', 'milk', 'dairy'], img: '095_flour-egg-milk-dairy.png', name: '奶油泡芙', description: '一口爆浆的美味泡芙。' },
  { id: 'food_096', 'main-res': 'flour', 'other-res': ['egg', 'milk', 'dairy', 'fruit'], img: '096_flour-egg-milk-dairy-fruit.png', name: '水果瑞士卷', description: '卷着奶油和水果的松软蛋糕卷。' },
  { id: 'food_097', 'main-res': 'flour', 'other-res': ['egg', 'milk', 'meat'], img: '097_flour-egg-milk-meat.png', name: '培根蛋饼', description: '咸香适口的早餐蛋饼。' },
  { id: 'food_098', 'main-res': 'flour', 'other-res': ['egg', 'fruit'], img: '098_flour-egg-fruit.png', name: '果酱夹心饼', description: '夹着自制果酱的酥脆饼干。' },
  { id: 'food_099', 'main-res': 'flour', 'other-res': ['egg', 'milk', 'dairy'], img: '099_flour-egg-milk-dairy.png', name: '千层蛋糕', description: '无数层薄饼与奶油堆叠的口感盛宴。' },
  { id: 'food_100', 'main-res': 'flour', 'other-res': ['egg', 'milk', 'dairy', 'fruit'], img: '100_flour-egg-milk-dairy-fruit.png', name: '芭菲', description: '装在杯子里的华丽甜点汇演。' },
  { id: 'food_101', 'main-res': 'flour', 'other-res': ['egg', 'milk', 'dairy', 'melons'], img: '101_flour-egg-milk-dairy-melons.png', name: '蜜瓜包', description: '外皮酥脆如蜜瓜纹路的面包。' },
  { id: 'food_102', 'main-res': 'flour', 'other-res': ['milk', 'dairy', 'fruit'], img: '102_flour-milk-dairy-fruit.png', name: '水果奶冻卷', description: '包裹着奶冻和水果的蛋糕卷。' },
  { id: 'food_103', 'main-res': 'flour', 'other-res': ['milk', 'dairy', 'fruit'], img: '103_flour-milk-dairy-fruit.png', name: '酸奶水果杯', description: '麦片、酸奶与水果的健康组合。' },
  { id: 'food_104', 'main-res': 'flour', 'other-res': ['egg', 'milk', 'dairy', 'fruit'], img: '104_flour-egg-milk-dairy-fruit.png', name: '草莓奶油蛋糕', description: '经典的红白配色，永恒的美味。' },
  { id: 'food_105', 'main-res': 'flour', 'other-res': ['egg', 'milk', 'dairy'], img: '105_flour-egg-milk-dairy.png', name: '原味戚风', description: '轻盈如云的戚风蛋糕。' },
  { id: 'food_106', 'main-res': 'flour', 'other-res': ['dairy'], img: '106_flour-dairy.png', name: '芝士条', description: '浓郁的咸味芝士零食。' },
  { id: 'food_107', 'main-res': 'flour', 'other-res': ['egg'], img: '107_flour-egg.png', name: '鸡蛋饼干', description: '充满蛋香的小饼干。' },
  { id: 'food_108', 'main-res': 'flour', 'other-res': ['egg', 'dairy'], img: '108_flour-egg-dairy.png', name: '奶酪球', description: '一口一个的香酥奶酪球。' },
  { id: 'food_109', 'main-res': 'flour', 'other-res': ['egg', 'fruit'], img: '109_flour-egg-fruit.png', name: '水果麦芬', description: '镶嵌着果肉的杯子蛋糕。' },
  { id: 'food_110', 'main-res': 'bread', 'other-res': [], img: '110_bread.png', name: '手工切片面包', description: '旅店自制的朴实切片面包。' },
  { id: 'food_111', 'main-res': 'bread', 'other-res': ['egg', 'meat'], img: '111_bread-egg-meat.png', name: '豪华三明治', description: '夹着厚蛋烧和肉排的豪华三明治。' },
  { id: 'food_112', 'main-res': 'bread', 'other-res': ['vegetable', 'tomatoes'], img: '112_bread-vegetable-tomatoes.png', name: '蔬菜三明治', description: '清爽健康的蔬菜夹心三明治。' },
  { id: 'food_113', 'main-res': 'bread', 'other-res': ['vegetable', 'tomatoes', 'dairy'], img: '113_bread-vegetable-tomatoes-dairy.png', name: '芝士蔬菜三明治', description: '加入芝士片，风味更佳。' },
  { id: 'food_114', 'main-res': 'bread', 'other-res': ['vegetable', 'tomatoes', 'meat'], img: '114_bread-vegetable-tomatoes-meat.png', name: 'BLT三明治', description: '培根、生菜、番茄的经典组合。' },
  { id: 'food_115', 'main-res': 'bread', 'other-res': ['vegetable', 'tomatoes', 'meat', 'dairy'], img: '115_bread-vegetable-tomatoes-meat-dairy.png', name: '全家福三明治', description: '什么都有的巨无霸三明治。' },
  { id: 'food_116', 'main-res': 'bread', 'other-res': ['vegetable', 'tomatoes', 'meat', 'dairy'], img: '116_bread-vegetable-tomatoes-meat-dairy.png', name: '热压三明治', description: '经过热压烘烤，外皮酥脆，芝士融化。' },
  { id: 'food_117', 'main-res': 'bread', 'other-res': ['vegetable', 'tomatoes', 'meat', 'dairy'], img: '117_bread-vegetable-tomatoes-meat-dairy.png', name: '潜艇堡', description: '长条面包夹满丰富馅料。' },
  { id: 'food_118', 'main-res': 'bread', 'other-res': ['dairy'], img: '118_bread-dairy.png', name: '黄油吐司', description: '涂抹黄油烤至金黄的吐司。' },
  { id: 'food_119', 'main-res': 'bread', 'other-res': ['dairy'], img: '119_bread-dairy.png', name: '蒜香法棍', description: '涂抹蒜香黄油烤制的法棍切片。' },
  { id: 'food_120', 'main-res': 'bread', 'other-res': ['dairy', 'carrot', 'potato', 'mushroom'], img: '120_bread-dairy-carrot-potato-mushroom.png', name: '奶油炖菜面包碗', description: '挖空的面包中盛满奶油炖菜。' },
  { id: 'food_121', 'main-res': 'bread', 'other-res': ['dairy', 'milk'], img: '121_bread-dairy-milk.png', name: '法式吐司', description: '浸泡蛋奶液煎制的吐司，松软香甜。' },
  { id: 'food_122', 'main-res': 'bread', 'other-res': ['bean', 'rice'], img: '122_bread-bean-rice.png', name: '炒面面包', description: '虽然叫炒面面包，但其实夹的是炒饭和豆子？' },
  { id: 'food_123', 'main-res': 'bread', 'other-res': ['dairy', 'bean'], img: '123_bread-dairy-bean.png', name: '红豆黄油面包', description: '红豆沙与厚切黄油的罪恶组合。' },
  { id: 'food_124', 'main-res': 'rice', 'other-res': [], img: '124_rice.png', name: '白米饭', description: '热腾腾、晶莹剔透的白米饭。' },
  { id: 'food_125', 'main-res': 'rice', 'other-res': ['meat'], img: '125_rice-meat.png', name: '肉燥饭', description: '淋上香浓肉燥的米饭。' },
  { id: 'food_126', 'main-res': 'rice', 'other-res': ['fish'], img: '126_rice-fish.png', name: '海鲜丼', description: '铺满新鲜鱼生的米饭。' },
  { id: 'food_127', 'main-res': 'rice', 'other-res': ['shrimp', 'flour'], img: '127_rice-shrimp-flour.png', name: '天妇罗盖饭', description: '炸虾天妇罗配上甜咸酱汁。' },
  { id: 'food_128', 'main-res': 'rice', 'other-res': ['tomatoes'], img: '128_rice-tomatoes.png', name: '番茄烩饭', description: '吸满番茄汤汁的意大利烩饭。' },
  { id: 'food_129', 'main-res': 'rice', 'other-res': ['meat', 'carrot', 'potato'], img: '129_rice-meat-carrot-potato.png', name: '咖喱饭', description: '香辛料浓郁的咖喱，米饭杀手。' },
  { id: 'food_130', 'main-res': 'rice', 'other-res': ['meat', 'flour', 'carrot', 'tomatoes'], img: '130_rice-meat-flour-carrot-tomatoes.png', name: '炸猪排咖喱', description: '咖喱饭配上酥脆炸猪排，顶级享受。' },
  { id: 'food_131', 'main-res': 'rice', 'other-res': ['egg', 'carrot', 'tomatoes'], img: '131_rice-egg-carrot-tomatoes.png', name: '蛋包饭', description: '用蛋皮包裹番茄炒饭，画上爱心。' },
  { id: 'food_132', 'main-res': 'rice', 'other-res': [], img: '132_rice.png', name: '饭团', description: '方便携带的盐味饭团。' },
  { id: 'food_133', 'main-res': 'rice', 'other-res': ['bean'], img: '133_rice-bean.png', name: '赤豆饭', description: '喜庆日子吃的红豆糯米饭。' },
  { id: 'food_134', 'main-res': 'rice', 'other-res': ['bean', 'carrot', 'vegetable'], img: '134_rice-bean-carrot-vegetable.png', name: '什锦菜饭', description: '蔬菜和米饭焖煮而成，清香扑鼻。' },
  { id: 'food_135', 'main-res': 'rice', 'other-res': ['bean', 'carrot', 'tomatoes'], img: '135_rice-bean-carrot-tomatoes.png', name: '墨西哥饭', description: '辛辣风味的豆子番茄饭。' },
  { id: 'food_136', 'main-res': 'rice', 'other-res': ['shrimp', 'mussel', 'fruit', 'tomatoes'], img: '136_rice-shrimp-mussel-fruit-tomatoes.png', name: '海鲜菠萝饭', description: '装在菠萝里的海鲜炒饭，酸甜开胃。' },
  { id: 'food_137', 'main-res': 'vegetable', 'other-res': [], img: '137_vegetable.png', name: '生菜沙拉', description: '新鲜采摘的生菜，淋上油醋汁。' },
  { id: 'food_138', 'main-res': 'vegetable', 'other-res': ['tomatoes'], img: '138_vegetable-tomatoes.png', name: '番茄沙拉', description: '番茄切片配上罗勒叶。' },
  { id: 'food_139', 'main-res': 'vegetable', 'other-res': ['tomatoes'], img: '139_vegetable-tomatoes.png', name: '混合蔬菜沙拉', description: '多种颜色的蔬菜组合，营养均衡。' },
  { id: 'food_140', 'main-res': 'vegetable', 'other-res': ['meat', 'dairy'], img: '140_vegetable-meat-dairy.png', name: '凯撒沙拉', description: '配上培根碎、面包丁和芝士粉的经典沙拉。' },
  { id: 'food_141', 'main-res': 'vegetable', 'other-res': ['jelly'], img: '141_vegetable-jelly.png', name: '蔬菜冻', description: '将蔬菜封存在透明的肉汤冻中。' },
  { id: 'food_142', 'main-res': 'jelly', 'other-res': ['fruit'], img: '142_jelly-fruit.png', name: '水果果冻', description: '晶莹剔透，包裹着新鲜果肉。' },
  { id: 'food_143', 'main-res': 'jelly', 'other-res': ['fruit'], img: '143_jelly-fruit.png', name: '什锦果冻', description: '多种水果口味的果冻拼盘。' },
  { id: 'food_144', 'main-res': 'jelly', 'other-res': ['fruit'], img: '144_jelly-fruit.png', name: '果冻杯', description: '方便食用的杯装果冻。' },
  { id: 'food_145', 'main-res': 'jelly', 'other-res': ['milk', 'fruit'], img: '145_jelly-milk-fruit.png', name: '牛奶布丁', description: '口感嫩滑，奶香浓郁。' },
  { id: 'food_146', 'main-res': 'jelly', 'other-res': ['fruit', 'flour', 'dairy'], img: '146_jelly-fruit-flour-dairy.png', name: '果冻慕斯', description: '口感轻盈的慕斯蛋糕，顶层是果冻。' },
  { id: 'food_147', 'main-res': 'jelly', 'other-res': ['fruit'], img: '147_jelly-fruit.png', name: '水晶果球', description: '球形的水果果冻，像宝石一样。' },
  { id: 'food_148', 'main-res': 'jelly', 'other-res': ['fruit', 'flour', 'egg', 'dairy'], img: '148_jelly-fruit-flour-egg-dairy.png', name: '果冻蛋糕', description: '夹层中含有果冻的清爽蛋糕。' },
  { id: 'food_149', 'main-res': 'fruit', 'other-res': [], img: '149_fruit.png', name: '鲜果切盘', description: '时令水果的拼盘，饭后最佳甜点。' },
  { id: 'food_150', 'main-res': 'fruit', 'other-res': ['jelly'], img: '150_fruit-jelly.png', name: '水果捞', description: '水果丁浸泡在糖水或果汁中。' },
  { id: 'food_151', 'main-res': 'fruit', 'other-res': ['flour', 'milk', 'dairy'], img: '151_fruit-flour-milk-dairy.png', name: '水果班戟', description: '奶油和水果被包裹在软糯的冰皮中。' },
  { id: 'food_152', 'main-res': 'egg', 'other-res': [], img: '152_egg.png', name: '水煮蛋', description: '简单的白水煮蛋，营养丰富。' },
  { id: 'food_153', 'main-res': 'egg', 'other-res': ['egg'], img: '153_egg-egg.png', name: '双黄蛋', description: '幸运的双黄蛋。' },
  { id: 'food_154', 'main-res': 'egg', 'other-res': ['tomatoes'], img: '154_egg-tomatoes.png', name: '番茄炒蛋', description: '无论在哪里都是国民级的家常菜。' },
  { id: 'food_155', 'main-res': 'egg', 'other-res': ['tomatoes', 'dairy'], img: '155_egg-tomatoes-dairy.png', name: '番茄芝士烘蛋', description: '加入芝士和番茄的西式烘蛋。' },
  { id: 'food_156', 'main-res': 'egg', 'other-res': ['rice'], img: '156_egg-rice.png', name: '鸡蛋盖饭', description: '生鸡蛋拌饭，淋上酱油，简单的美味。' },
  { id: 'food_157', 'main-res': 'egg', 'other-res': ['rice', 'dairy'], img: '157_egg-rice-dairy.png', name: '芝士蛋饭', description: '热腾腾的米饭拌入生蛋和芝士粉。' },
  { id: 'food_158', 'main-res': 'egg', 'other-res': ['dairy', 'jelly'], img: '158_egg-dairy-jelly.png', name: '焦糖布丁', description: '经典的鸡蛋布丁，表面是脆脆的焦糖。' },
  { id: 'food_159', 'main-res': 'egg', 'other-res': ['dairy', 'jelly', 'fruit'], img: '159_egg-dairy-jelly-fruit.png', name: '水果布丁百汇', description: '布丁配上水果和奶油的豪华甜品。' },
  { id: 'food_160', 'main-res': 'mushroom', 'other-res': [], img: '160_mushroom.png', name: '烤蘑菇', description: '撒点盐烤蘑菇，鲜汁直冒。' },
  { id: 'food_161', 'main-res': 'mushroom', 'other-res': [], img: '161_mushroom.png', name: '黄油煎菌', description: '用黄油煎出的蘑菇，香气逼人。' },
  { id: 'food_162', 'main-res': 'mushroom', 'other-res': ['mushroom'], img: '162_mushroom-mushroom.png', name: '杂菌煲', description: '汇集多种菌类的鲜美砂锅。' },
  { id: 'food_163', 'main-res': 'melons', 'other-res': [], img: '163_melons.png', name: '蜜瓜切片', description: '香甜多汁的蜜瓜。' },
  { id: 'food_164', 'main-res': 'melons', 'other-res': ['milk'], img: '164_melons-milk.png', name: '蜜瓜奶昔', description: '香甜的蜜瓜撞上醇厚的牛奶，清凉解暑。' },
];
